"""Generates a Fabric Git-sync-native mirror of notebooks/** under /fabric.

Fabric's Git integration requires each item as a `<DisplayName>.Notebook/`
folder containing `notebook-content.py`, `.platform`, and (for notebooks
that import a sibling `transforms.py`) `Resources/builtin/transforms.py`.
The `notebooks/**/{notebook.py,transforms.py}` tree stays the single source
of truth for logic and tests -- this script only copies from it. Nothing
under /fabric should be hand-edited; regenerate it instead.

The Fabric workspace's Git connection points at this /fabric folder (its
`directoryName` git setting), not the repo root, so the tested repo layout
under notebooks/ never has to match Fabric's item-serialization format.

Usage: python scripts/build_fabric_sync.py
"""

from __future__ import annotations

import json
import shutil
import uuid
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
FABRIC_SYNC_ROOT = REPO_ROOT / "fabric"

# Fixed namespace for deriving each item's logicalId. Do not change this --
# changing it would make every regenerated item look "new" to Fabric's Git
# sync instead of an update to the same item.
LOGICAL_ID_NAMESPACE = uuid.UUID("6f3f6a0e-6b1a-4f0b-9c3a-8e6a2b6c9a4d")

# (layer, module folder under notebooks/<layer>/, Fabric item display name)
ITEMS = [
    ("bronze", "fmp", "bronze_fmp"),
    ("bronze", "gus", "bronze_gus"),
    ("bronze", "nbp", "bronze_nbp"),
    ("bronze", "stooq", "bronze_stooq"),
    ("silver", "fx_rates", "silver_fx_rates"),
    ("silver", "prices", "silver_prices"),
    ("silver", "fundamentals", "silver_fundamentals"),
    ("silver", "macro", "silver_macro"),
    ("gold", "dim_company", "gold_dim_company"),
    ("gold", "dim_date", "gold_dim_date"),
    ("gold", "fact_prices", "gold_fact_prices"),
    ("gold", "fact_fundamentals", "gold_fact_fundamentals"),
    ("gold", "fact_macro", "gold_fact_macro"),
    ("quality", "reconciliation", "quality_reconciliation"),
]


def build_platform(display_name: str) -> bytes:
    """Build a Notebook item's .platform descriptor with a stable logicalId."""
    logical_id = str(uuid.uuid5(LOGICAL_ID_NAMESPACE, display_name))
    platform_obj = {
        "$schema": (
            "https://developer.microsoft.com/json-schemas/fabric/gitIntegration/"
            "platformProperties/2.0.0/schema.json"
        ),
        "metadata": {"type": "Notebook", "displayName": display_name},
        "config": {"version": "2.0", "logicalId": logical_id},
    }
    return (json.dumps(platform_obj, indent=2) + "\n").encode("utf-8")


def main() -> None:
    if FABRIC_SYNC_ROOT.exists():
        shutil.rmtree(FABRIC_SYNC_ROOT)
    FABRIC_SYNC_ROOT.mkdir(parents=True)

    for layer, module_name, display_name in ITEMS:
        source_dir = REPO_ROOT / "notebooks" / layer / module_name
        notebook_py = source_dir / "notebook.py"
        transforms_py = source_dir / "transforms.py"
        if not notebook_py.exists():
            raise FileNotFoundError(notebook_py)

        item_dir = FABRIC_SYNC_ROOT / f"{display_name}.Notebook"
        item_dir.mkdir(parents=True)

        (item_dir / "notebook-content.py").write_bytes(notebook_py.read_bytes())
        (item_dir / ".platform").write_bytes(build_platform(display_name))

        if transforms_py.exists():
            resources_dir = item_dir / "Resources" / "builtin"
            resources_dir.mkdir(parents=True)
            (resources_dir / "transforms.py").write_bytes(transforms_py.read_bytes())

    readme = FABRIC_SYNC_ROOT / "README.md"
    readme.write_text(
        "# Generated -- do not edit by hand\n\n"
        "This tree is generated by `scripts/build_fabric_sync.py` from "
        "`notebooks/**`. It exists only so Fabric's Git integration "
        "(pointed at this folder, not the repo root) can sync real "
        "Notebook items -- Fabric requires each item as a "
        "`<DisplayName>.Notebook/` folder with a `.platform` descriptor, "
        "which `notebooks/**` deliberately doesn't have, to keep it plainly "
        "testable/importable outside Fabric.\n\n"
        "Regenerate after any `notebook.py`/`transforms.py` change:\n\n"
        "```\npython scripts/build_fabric_sync.py\n```\n",
        encoding="utf-8",
    )

    print(f"Generated {len(ITEMS)} Fabric notebook items under {FABRIC_SYNC_ROOT}")


if __name__ == "__main__":
    main()
